Maven: command line client scripts generation added; assembly which includes both JavaHL API and its SVNKit implementation added.

diff --git a/svnkit-cli/src/main/scripts/jsvn b/svnkit-cli/src/main/scripts/jsvn
--- a/svnkit-cli/src/main/scripts/jsvn
+++ b/svnkit-cli/src/main/scripts/jsvn
@@ -1,40 +1,74 @@
-#!/bin/sh
+BASEDIR=`dirname $0`/..
+BASEDIR=`(cd "$BASEDIR"; pwd)`
 
 cygwin=false;
+darwin=false;
 case "`uname`" in
   CYGWIN*) cygwin=true ;;
+  Darwin*) darwin=true
+           if [ -z "$JAVA_VERSION" ] ; then
+             JAVA_VERSION="CurrentJDK"
+           else
+             echo "Using Java version: $JAVA_VERSION"
+           fi
+           if [ -z "$JAVA_HOME" ] ; then
+             JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/${JAVA_VERSION}/Home
+           fi
+           ;;
 esac
 
-old_wd=`pwd`
-
-progname=`basename "$0"`
-linkdir=`dirname "$0"`
-
-cd "$linkdir"
-prg="$progname"
-
-while [ -h "$prg" ] ; do
-  ls=`ls -ld "$prg"`
-  link=`expr "$ls" : '.*-> \(.*\)$'`
-  if expr "$link" : '.*/.*' > /dev/null; then
-    prg="$link"
-  else
-    prg="`dirname $prg`/$link"
+if [ -z "$JAVA_HOME" ] ; then
+  if [ -r /etc/gentoo-release ] ; then
+    JAVA_HOME=`java-config --jre-home`
   fi
-done
-
-SVNKIT_HOME=`dirname $prg`
-SVNKIT_HOME=`cd "$SVNKIT_HOME" ; pwd`
-
-cd "$old_wd"
-
-SVNKIT_CP="$SVNKIT_HOME/svnkit.jar":"$SVNKIT_HOME/svnkit-cli.jar":"$SVNKIT_HOME/trilead.jar":"$SVNKIT_HOME/jna.jar":"$SVNKIT_HOME/sqljet.%sqljet.version%.jar":"$SVNKIT_HOME/antlr-runtime-%antlr.version%.jar"
-
-if $cygwin ; then
-  SVNKIT_CP=`cygpath --windows --path "$SVNKIT_CP"`
 fi
 
-SVNKIT_OPTIONS="$SVNKIT_OPTIONS -Dsun.io.useCanonCaches=false -Djava.util.logging.config.file=$SVNKIT_HOME/logging.properties"
+# For Cygwin, ensure paths are in UNIX format before anything is touched
+if $cygwin ; then
+  [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
+  [ -n "$CLASSPATH" ] && CLASSPATH=`cygpath --path --unix "$CLASSPATH"`
+fi
 
-SVNKIT_MAINCLASS=org.tmatesoft.svn.cli.svn.SVN
-"$JAVA_HOME/bin/java" $SVNKIT_OPTIONS -cp $SVNKIT_CP $SVNKIT_MAINCLASS "$@"
+# If a specific java binary isn't specified search for the standard 'java' binary
+if [ -z "$JAVACMD" ] ; then
+  if [ -n "$JAVA_HOME"  ] ; then
+    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
+      # IBM's JDK on AIX uses strange locations for the executables
+      JAVACMD="$JAVA_HOME/jre/sh/java"
+    else
+      JAVACMD="$JAVA_HOME/bin/java"
+    fi
+  else
+    JAVACMD=`which java`
+  fi
+fi
+
+if [ ! -x "$JAVACMD" ] ; then
+  echo "Error: JAVA_HOME is not defined correctly."
+  echo "  We cannot execute $JAVACMD"
+  exit 1
+fi
+
+if [ -z "$SVNKIT_LIB" ]
+then
+  SVNKIT_LIB="$BASEDIR"/lib
+fi
+
+${dependency:CLASSPATH=$CLASSPATH:"$SVNKIT_LIB/${dependency.file}"}
+
+EXTRA_JVM_ARGUMENTS="-Djava.util.logging.config.file=logging.properties -Dsun.io.useCanonCaches=false"
+
+# For Cygwin, switch paths to Windows format before running java
+if $cygwin; then
+  [ -n "$CLASSPATH" ] && CLASSPATH=`cygpath --path --windows "$CLASSPATH"`
+  [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --path --windows "$JAVA_HOME"`
+  [ -n "$HOME" ] && HOME=`cygpath --path --windows "$HOME"`
+  [ -n "$BASEDIR" ] && BASEDIR=`cygpath --path --windows "$BASEDIR"`
+  [ -n "$REPO" ] && REPO=`cygpath --path --windows "$REPO"`
+fi
+
+exec "$JAVACMD" $JAVA_OPTS \
+  $EXTRA_JVM_ARGUMENTS \
+  -classpath "$CLASSPATH" \
+  ${mainClass} \
+  "$@"
